{
  "N": 100,
  "beta": 3.9148165466037645,
  "dt": 0.0006892640504700272,
  "gaussian_stimulus_width": 5,
  "h": -0.16732671626923667,
  "intensity_scale_factor": 10.942015602644785,
  "sigma_exc": 4.173955119706477,
  "sigma_inh": 12.639611750433119,
  "tau": 0.006696879674637498,
  "theta": 0.05299174094862421,
  "w_exc": 1.366368413883727,
  "w_inh": 1.417175751949093
}