{
  "N": 100,
  "beta": 2.047035939542551,
  "dt": 0.0007685985350006151,
  "gaussian_stimulus_width": 6,
  "h": -0.3040240162652609,
  "intensity_scale_factor": 11.134526352126645,
  "sigma_exc": 3.5327390268443004,
  "sigma_inh": 10.36592880122392,
  "tau": 0.005969100766565657,
  "theta": 0.016530090277236925,
  "w_exc": 2.2785398778436514,
  "w_inh": 1.0709031655325965
}